# Generated by Django 2.1 on 2018-08-15 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='requset_pu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_saved', models.DateTimeField(auto_now_add=True)),
                ('combo_kind', models.CharField(choices=[(1, 'اضطراری'), (2, 'فوری'), (3, 'عادی')], max_length=120)),
                ('title', models.CharField(max_length=60)),
                ('dead_line', models.CharField(max_length=500)),
                ('ex_request', models.TextField()),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
