# Generated by Django 2.1 on 2018-08-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requset_pu',
            name='combo_kind',
            field=models.CharField(choices=[('1', 'اضطراری'), ('2', 'فوری'), ('3', 'عادی')], max_length=120),
        ),
    ]
